### ISSUE TITLE
Compilation Problem : 

### ISSUE THREAD

**Issue by benur75** [Ryzee119/spi2par2019#2]
Hello Ryan,
could you tell me what is wrong on ly fresh install, when I compile I ahve such issue: using your latest files: ( which library did you include in your Arduino software - I use 1.8.10) 
Bye!

sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::setRowOffsets(int, int, int, int)'

etc

**Comment by Ryzee119** [comment]
Arduino 1.8.10 will only move the .ino file to the sketch folder. Please ensure you have moved all the supporting files to this folder too (src folder, and header files)

**Comment by benur75** [comment]
look at the logs:
C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::setRowOffsets(int, int, int, int)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::pulseEnable()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::write4bits(unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::write8bits(unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::send(unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::clear()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::home()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::setCursor(unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::noDisplay()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::display()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::begin(unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::init(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::noCursor()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::cursor()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::noBlink()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::blink()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::scrollDisplayLeft()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::scrollDisplayRight()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::leftToRight()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::rightToLeft()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::autoscroll()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::noAutoscroll()'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\lcd\lcd.cpp.o (symbol from plugin): In function `LiquidCrystal::setRowOffsets(int, int, int, int)':

(.text+0x0): multiple definition of `LiquidCrystal::createChar(unsigned char, unsigned char*)'

C:\Users\STPHAN~1\AppData\Local\Temp\arduino_build_172675\sketch\src\HD44780\HD44780.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Leonardo.

**Comment by benur75** [comment]
Could it be when you last cleanup files ? Or did I miss something ?
bye

**Comment by Ryzee119** [comment]
In the src folder, there is a folder called HD44780. Delete this folder and recompile. Please let me know if that fixes the issue.

**Comment by benur75** [comment]
Good evening Ryan,
now it works. Thx.
bye

**Comment by Ryzee119** [comment]
Ive just pushed a new update with some bug fixes. You should try this version too

**Comment by benur75** [comment]
Hello Ryan,
I will test it this month. I have to first assemble OpenXenium. I have all component received. 
Is is possible to use spi2par2019 without Xenium or Openxenium ?
bye

**Comment by Ryzee119** [comment]
Compilation issues resolved.
